import json
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "weather_data" / "processed" / "real_ml"
MODEL_DIR = OUTPUT_DIR / "model3"
METADATA_FILE = MODEL_DIR / "training_metadata.json"
MODEL_METRICS_FILE = MODEL_DIR / "evaluation_metrics.json"
LADDER_FILE = OUTPUT_DIR / "M1_REAL_MODEL_LADDER_BACKTEST_2025.json"
OUTPUT_FILE = OUTPUT_DIR / "M1_DATA_HANDOFF.md"


def _load_json(path: Path) -> dict:
    if not path.is_file():
        raise FileNotFoundError(
            f"Required real training/evaluation artifact is missing: {path}"
        )
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"Could not read generated artifact {path}: {exc}") from exc


def _metric_lines(name: str, metrics: dict) -> list[str]:
    return [
        f"### {name}",
        "",
        f"- MAE: {metrics['mae']}",
        f"- RMSE: {metrics['rmse']}",
        f"- R²: {metrics['r2']}",
        "",
    ]


def generate_handoff() -> None:
    metadata = _load_json(METADATA_FILE)
    model_metrics = _load_json(MODEL_METRICS_FILE)
    ladder = _load_json(LADDER_FILE)

    lines = [
        "# VARUNA-AI Real-Data M1 Handoff",
        "",
        f"- Dataset: `{metadata['dataset']}`",
        f"- Dataset SHA-256: `{metadata['dataset_sha256']}`",
        f"- Model: `{metadata['model']}`",
        f"- Target: `{metadata['target']}`",
        f"- Training rows used: {metadata['rows']['train_used']}",
        f"- Validation rows: {metadata['rows']['validation']}",
        f"- Test rows: {metadata['rows']['test']}",
        "",
        "## Chronological Periods",
        "",
        f"- Train: {metadata['train_period'][0]} to {metadata['train_period'][1]}",
        f"- Validation: {metadata['validation_period'][0]} to {metadata['validation_period'][1]}",
        f"- Test: {metadata['test_period'][0]} to {metadata['test_period'][1]}",
        "",
        "## Fitted Model Evaluation",
        "",
    ]
    lines.extend(_metric_lines("Validation", model_metrics["validation"]))
    lines.extend(_metric_lines("Held-out test", model_metrics["test"]))
    lines.extend(["## Available Real-Data Model Ladder", ""])

    for level_name, level in ladder["levels"].items():
        lines.extend([f"### {level_name}", "", f"Status: {level['status']}", ""])
        if level["status"] == "unavailable":
            lines.extend([f"Reason: {level['reason']}", ""])
            continue
        for period_name in ("validation", "test"):
            metrics = level[period_name]
            lines.extend(
                [
                    f"{period_name.title()} MAE: {metrics['MAE']}",
                    f"{period_name.title()} RMSE: {metrics['RMSE']}",
                    f"{period_name.title()} mean bias: {metrics['Mean_Bias']}",
                    f"{period_name.title()} correlation: {metrics['Correlation']}",
                    "",
                ]
            )

    lines.extend(
        [
            "These metrics are read from outputs generated by the real-data pipeline. "
            "Unavailable model levels are not filled with sample, synthetic, or fallback results.",
            "",
        ]
    )
    OUTPUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Created real-data handoff: {OUTPUT_FILE}")


if __name__ == "__main__":
    generate_handoff()