# Generated by Django 6.1 on 2026-08-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=64)),
                ('zone', models.CharField(max_length=64)),
                ('centroid_lat', models.FloatField()),
                ('centroid_lon', models.FloatField()),
                ('polygon_geojson', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('run_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('initialization_time', models.DateTimeField()),
                ('valid_time', models.DateField()),
                ('lead_time_hours', models.IntegerField(default=24)),
                ('detected_regime', models.CharField(max_length=64)),
                ('regime_confidence', models.FloatField()),
                ('regime_probabilities_json', models.TextField(default='{}')),
                ('synoptic_features_json', models.TextField(default='{}')),
                ('model_version', models.CharField(default='VARUNA-Level3-XGB-v1.0.0', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=128)),
                ('model_version', models.CharField(max_length=64)),
                ('component', models.CharField(max_length=64)),
                ('dataset_version', models.CharField(max_length=32)),
                ('training_period', models.CharField(max_length=64)),
                ('val_period', models.CharField(max_length=32)),
                ('test_period', models.CharField(max_length=32)),
                ('metrics_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_nwp_mean_mm', models.FloatField()),
                ('corrected_mean_mm', models.FloatField()),
                ('corrected_max_mm', models.FloatField()),
                ('bias_correction_delta_mm', models.FloatField()),
                ('heavy_rain_probability', models.FloatField()),
                ('prob_exceed_115mm', models.FloatField(default=0.0)),
                ('prob_exceed_204mm', models.FloatField(default=0.0)),
                ('uncertainty_lower_10pct', models.FloatField()),
                ('uncertainty_upper_90pct', models.FloatField()),
                ('uncertainty_range_width', models.FloatField()),
                ('risk_code', models.CharField(default='GREEN', max_length=16)),
                ('risk_label', models.CharField(max_length=128)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='backend.district')),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_forecasts', to='backend.forecastrun')),
            ],
            options={
                'unique_together': {('forecast_run', 'district')},
            },
        ),
    ]
